apiVersion: v3
kind: service
metadata:
  name: istio-test
  description: An example Istio test application that shows metadata about the Google Kubernetes Engine (GKE) cluster.
  displayName: istio-test

  links:
    - name: istio-test
      type: repo
      provider: Github
      url: "https://github.com/osinfra-io/istio-test"

    - name: sb.gcp.osinfra.io
      type: other
      url: "https://sb.gcp.osinfra.io/istio-test/health"

    - name: us-east1-b.sb.gcp.osinfra.io
      type: other
      url: "https://us-east1-b.sb.gcp.osinfra.io/istio-test/health"

    - name: us-east4-a.sb.gcp.osinfra.io
      type: other
      url: "https://us-east4-a.sb.gcp.osinfra.io/istio-test/health"

    - name: nonprod.gcp.osinfra.io
      type: other
      url: "https://nonprod.gcp.osinfra.io/istio-test/health"

    - name: us-east1-b.nonprod.gcp.osinfra.io
      type: other
      url: "https://us-east1-b.nonprod.gcp.osinfra.io/istio-test/health"

    - name: us-east4-a.nonprod.gcp.osinfra.io
      type: other
      url: "https://us-east4-a.nonprod.gcp.osinfra.io/istio-test/health"

    - name: gcp.osinfra.io
      type: other
      url: "https://gcp.osinfra.io/istio-test/health"

    - name: us-east1-b.gcp.osinfra.io
      type: other
      url: "https://us-east1-b.gcp.osinfra.io/istio-test/health"

    - name: us-east4-a.gcp.osinfra.io
      type: other
      url: "https://us-east4-a.gcp.osinfra.io/istio-test/health"

  contacts:
    - type: email
      contact: platform-google-cloud-kubernetes@osinfra.io
    - type: google-chat
      contact: "https://mail.google.com/chat/u/0/#chat/space/AAAA1mERq4Q"

  owner: platform-google-cloud-kubernetes

spec:
  lifecycle: production
  tier: Zero
  type: web
  languages:
    - go

  dependsOn:
    - 'service:istio-gateway'

datadog:
  performanceData:
    tags:
      - 'service:istio-test'

  pipelines:
    fingerprints:
      - NabNkdMuNLxT
