apiVersion: v3
kind: service
metadata:
  name: gke-info-go
  description: An example Go application that shows information about the Google Kubernetes Engine (GKE) cluster.
  displayName: GKE Info Go

  links:
    - name: Sandbox
      type: other
      url: "https://sb.gcp.osinfra.io/gke-info-go/health"

    - name: "Sandbox: us-east1-b"
      type: other
      url: "https://us-east1-b.sb.gcp.osinfra.io/gke-info-go/health"

    - name: "Sandbox: us-east4-a"
      type: other
      url: "https://us-east4-a.sb.gcp.osinfra.io/gke-info-go/health"

    - name: Pre-Production
      type: other
      url: "https://pre-prod.gcp.osinfra.io/gke-info-go/health"

    - name: "Pre-Production: us-east1-b"
      type: other
      url: "https://us-east1-b.pre-prod.gcp.osinfra.io/gke-info-go/health"

    - name: "Pre-Production: us-east4-a"
      type: other
      url: "https://us-east4-a.pre-prod.gcp.osinfra.io/gke-info-go/health"

    - name: Production
      type: other
      url: "https://gcp.osinfra.io/gke-info-go/health"

    - name: "Production: us-east1-b"
      type: other
      url: "https://us-east1-b.gcp.osinfra.io/gke-info-go/health"

    - name: "Production: us-east4-a"
      type: other
      url: "https://us-east4-a.gcp.osinfra.io/gke-info-go/health"

  contacts:
    - type: email
      contact: platform-google-cloud-kubernetes@osinfra.io
    - type: google-chat
      contact: "https://mail.google.com/chat/u/0/#chat/space/AAAA1mERq4Q"

  owner: platform-google-cloud-kubernetes

spec:
  lifecycle: production
  tier: Zero
  type: web
  languages:
    - go

  dependsOn:
    - service:istio-gateway

datadog:
  performanceData:
    tags:
      - 'service:gke-info-go'
  pipelines:
    fingerprints:
      - NabNkdMuNLxT
