name: Docker Build and Test

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    name: Build and Test
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      # Checkout
      # https://github.com/marketplace/actions/checkout

      - name: Checkout
        uses: actions/checkout@v4

      # Docker Buildx
      # https://github.com/marketplace/actions/docker-setup-buildx

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      # Docker Login
      # https://github.com/marketplace/actions/docker-login

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and Test Docker images
      # https://github.com/marketplace/actions/build-and-push-docker-images

      - name: Build
        uses: docker/build-push-action@v5.3.0
        with:
          context: gke-info-go
          tags: |
            ghcr.io/osinfra-io/gke-info-go:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Test
        run: |
          docker run --rm ghcr.io/osinfra-io/gke-info-go:test
