name: Release

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build_and_push_us:
    name: "Sandbox Registry: us-docker.pkg.dev"
    uses: osinfra-io/github-misc-called-workflows/.github/workflows/build-and-push.yml@v0.1.7
    if: github.actor != 'dependabot[bot]'
    with:
      cache_from: type=registry,ref=us-docker.pkg.dev/plt-lz-services-tf7f-sb/plt-docker-standard/istio-test:latest
      cache_to: type=inline
      build_args: |
            DD_GIT_REPOSITORY_URL=https://github.com/${{ github.repository }}
            DD_GIT_COMMIT_SHA=${{ github.sha }}
      registry: us-docker.pkg.dev
      service_account: plt-istio-test-github@plt-lz-terraform-tf00-sb.iam.gserviceaccount.com
      tags: |
        us-docker.pkg.dev/plt-lz-services-tf7f-sb/plt-docker-standard/istio-test:${{ github.event.release.tag_name }}
        us-docker.pkg.dev/plt-lz-services-tf7f-sb/plt-docker-standard/istio-test:latest
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
